### ISSUE TITLE
写的很棒 受教了！感谢！

### ISSUE THREAD

**Issue by haoyuanzhe** [wang-zhq/triangle_count#1]

**Comment by WeitongZhai** [comment]
你好，你看懂这个代码了吗？能不能解释一下他到底用的什么算法？我从f_count那里开始看不懂了

**Comment by haoyuanzhe** [comment]
> 你好，你看懂这个代码了吗？能不能解释一下他到底用的什么算法？我从f_count那里开始看不懂了

好久没看了，刚大概看了一下，fcount算结点点的权值吧，后面那个变量计算的是顶点序号小于i的有多少个。总体思路大概是：对边排序，然后对有相同的顶点的两条边，查找是否有第三条边吧，排序的目的是防止重复计算。

**Comment by WeitongZhai** [comment]
他设置fcount的时候，把小于dim的部分全设为零了，然后小于n_edge的部分，自增一，那这样fcount永远不可能大于1啊。这一点我搞不懂。所以接下来fcount，f_addr, b_bak这些变量做了一堆循环，得出结果edge sorted，就很不明白他到底干了什么事。你能解释一下吗？谢谢了。

**Comment by haoyuanzhe** [comment]
> 他设置fcount的时候，把小于dim的部分全设为零了，然后小于n_edge的部分，自增一，那这样fcount永远不可能大于1啊。这一点我搞不懂。所以接下来fcount，f_addr, b_bak这些变量做了一堆循环，得出结果edge sorted，就很不明白他到底干了什么事。你能解释一下吗？谢谢了。

109-110行fcount赋值用了front吧？怎么可能永远不大于一呢

**Comment by WeitongZhai** [comment]
那应该是我理解的不对。f_count[front[i]]++，我以为这句话就是数组嵌套。请问这句话应该是什么意思？

**Comment by haoyuanzhe** [comment]
> 那应该是我理解的不对。f_count[front[i]]++，我以为这句话就是数组嵌套。请问这句话应该是什么意思？

front[i]表示的是某条边的起始点的序号啊，是一个数字，值得范围是0-|V|吧，你可以找个简单的图 带入到代码里面运行一下代码，有助于理解

**Comment by WeitongZhai** [comment]
for (i = 0; i < dim; i++)
        f_count[i] = 0;

    for (i = 0; i < n_edge; i++)
        f_count[front[i]]++;



你看啊，第一句把f_count这个数组小于dim的元素全赋值为零了，第二句是什么意思？到底是什么东西自增1了？

**Comment by haoyuanzhe** [comment]
> ```
> for (i = 0; i < dim; i++)
>     f_count[i] = 0;
> 
> for (i = 0; i < n_edge; i++)
>     f_count[front[i]]++;
> ```
> 
> 你看啊，第一句把f_count这个数组小于dim的元素全赋值为零了，第二句是什么意思？到底是什么东西自增1了？
for (i = 0; i < dim; i++)
    f_count[i] = 0;
这两行是数组初始化
 f_count[front[i]]++;
这里数组下标是front[i]，仔细一点哇
