### ISSUE TITLE
从f_count那里开始看不懂了

### ISSUE THREAD

**Issue by WeitongZhai** [wang-zhq/triangle_count#2]
你好，能不能解释一下算法？从f_count那里开始看不懂了

**Comment by haoyuanzhe** [comment]
好久没看了，刚大概看了一下，fcount算结点点的权值吧，后面那个变量计算的是顶点序号小于i的有多少个。总体思路大概是：对边排序，然后对有相同的顶点的两条边，查找是否有第三条边吧，排序的目的是防止重复计算。

**Comment by wang-zhq** [comment]
请移步另一个项目：）
